### PR TITLE
Add an option --frontmatter_tags to control whether generate  tags of markdown's front matter.

### PR DESCRIPTION
**Pull request by incfly**
I found it not very helpful when tags are generated based on the `/path/to/the/dokukiwiki`. Additionally it may generate an empty "" tag which cause some problem for hugo to even compile the markdown.

### CODE REVIEW

**Comment by incfly** [comment]
@wgroeneveld

**Comment by wgroeneveld** [comment]
Thanks a lot! 
Would you be so kind to document your added option in the README.md?
Then I'll merge the request.

**Comment by incfly** [comment]
@wgroeneveld Done.

**Comment by incfly** [comment]
@wgroeneveld PTAL, thanks

**Comment by wgroeneveld** [comment]
Sorry, totally lost sight of this! Thanks

**Pull request merged**
